### ISSUE TITLE
Got issue with Pylance in list[str] Line 6 in youtube_service.py 

### ISSUE THREAD

**Issue by mopkaloppt** [coskundeniz/youtube-comments-sentiment-analyzer#1]
Line 6 in youtube_service.py 
I have an issue with Pylance, the error says _"Subscript for class "list" will generate runtime exception; enclose type annotation in quotesPylance"_
I tried to fix it following this [stackoverflow post](https://stackoverflow.com/questions/69426453/declaration-of-list-of-type-python) by putting **from __future__ import annotations** at the top of this file. 
The error doesn't go away and the code failed.

Could you please help? I really would like to use your code for youtube comments sentiment analysis. 

I'm on Macbook running Big Sur.  I'm using python 3.8

**Comment by coskundeniz** [comment]
Use like this

```
from typing import List

variable: List[str]
```

**Comment by mopkaloppt** [comment]
Code works now. I've got the result, thank you so much :)
